# لینک‌های حمایت مالی از پروژه RebLawBot و بازی دادگاه مجازی
custom:
  - https://t.me/Rebwar6384
  - https://t.me/RebLCBot
  - https://tonkeeper.com/transfer/UQBkRlKAi6Rk4EuZqJ8QrxDgugKK1kLUS6Yp4lOE6MPiRkGW

